name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install mdbook
      run: |
        cargo install mdbook --no-default-features --features search --vers "^0.4" --locked
        cargo install mdbook-mermaid
        cargo install mdbook-admonish
    - name: Build
      run: mdbook build
    # share between different jobs
    - uses: actions/upload-artifact@v3
      with:
        name: book
        path: book/